### ISSUE TITLE
Can't uncheck Github Pages in NameCheap Domain Checkout

### ISSUE THREAD

**Issue by berhanwa** [susanBuck/e2-fall22#4]
Hi everyone, I'm working through the domain video for week 2. When I tried completing the checkout process for my domain name on [nc.me](http://nc.me/), it wouldn't let me leave the Github pages section unchecked.

Is there a workaround for this?

**Comment by anc6314** [comment]
After trying a few times, I just left it checked and went on thru the rest of the docs.  No issues so far!

**Comment by kristinjohnson1** [comment]
Hi all, I'm having the same problem as @berhanwa. Doesn't seem to want to work in any browser.  Any suggestions?

Update:  I also got it!

**Comment by susanBuck** [comment]
If it won't let you uncheck Github pages, it's okay to proceed forward. 

When you get to the part where you update your DNS settings you may/probably will see an existing record that points to an IP address that will correspond to Github pages. When you see this, simply delete this existing record before creating your own.

If that doesn't work as expected, let me know!

**Comment by berhanwa** [comment]
Hi @susanBuck, your suggestion worked! I had several records I needed to delete later on in my DNS settings, and everything turned out fine. Thank you ☺️

**Comment by traveler9878** [comment]
I had the same problem, it's a radio button that fails validation if it's unchecked and it's the only option... I also just let it be checked and then ignored anything related to github afterwards.   I think I had to delete 2 A records and change one to point to DigitalOcean.  It's a bug in their website.

**Comment by kgondim** [comment]
> Hi everyone, I'm working through the domain video for week 2. When I tried completing the checkout process for my domain name on [nc.me](http://nc.me/), it wouldn't let me leave the Github pages section unchecked.
> 
> Is there a workaround for this?

## I had the same problem
#### I just left it checked. When namecheap tried to connect to my Github (*maybe I'm using the wrong terminology here*), it wouldn't because my Github account was created with a different email address, not my Harvard email address used for namecheap. Hopefully, that will not interfere the way we need to have our various services connected this semester. *I had no problems setting up the infrastructure from this week's lectures.*

> I had the same problem, it's a radio button that fails validation if it's unchecked and it's the only option... I also just let it be checked and then ignored anything related to github afterwards. I think I had to delete 2 A records and change one to point to DigitalOcean. It's a bug in their website.

#### I also deleted records that didn't relate to the records we were instructed to configure in this week's lectures, so I guess I inadvertently prevented a problem without knowing it. 🙂

**Comment by susanBuck** [comment]
Closing this thread since everyone should have set up their domains by now. 

Thanks everyone for your notes on this issue. I'll be sure to check on this again in future semesters and guide students accordingly.
