### ISSUE TITLE
Error message when trying to submit review after last week 13 video

### ISSUE THREAD

**Issue by kgondim** [susanBuck/e2-fall22#46]
@susanBuck After going through all the videos and coding as instructed, I'm getting an error message when I try to submit a review from the webpage that I believe is indicating the 'product_id' is undefined. I'm guessing the saveReview method is throwing the error.

<img width="784" alt="Screen Shot 2022-11-26 at 4 02 34 PM" src="https://user-images.githubusercontent.com/98433632/204108805-2a38496e-bb2b-466e-a6ec-acd0187a7e27.png">

I'm not entirely sure if this is the issue, but either way, it is not clear to me where we have defined 'product_id' 
+ In the show view, the value {{ $product['product_id'] }} is being inserted in the hidden input field, and we've created a table with that field, but not sure where 'product_id' is coming from or where it is defined. 
+ When we seed the review, we've created a method to generate that 'product_id' it seems, but its not clear where that id should be coming from otherwise when manually inputted by user. 
+ If we were already getting into relational tables, I would just use the id/PK instead, but we're not there yet in this course.

Any guidance would be greatly appreciated--thank you!

**Comment by susanBuck** [comment]
Hi @kgondim -

This line:
```html
<input type='hidden' name='product_id' value='{{ $product['product_id'] }}'>
```

Should be:
```html
<input type='hidden' name='product_id' value='{{ $product['id'] }}'>
```

The difference is in the _value_ - it should be set to `$product['id']` instead of `$product['product_id']`. This is referring to the `id` field set up with the products table when we use the [_createTable_](https://hesweb.dev/e2/notes/php/e2framework/database#createtable) method.

We only need to reference `product_id` when working in the context of the reviews table/data.

Does that help clarify? Let me know if it's still unclear - happy to elaborate further!

**Comment by kgondim** [comment]
@susanBuck That makes much more sense--thank you!

**Comment by susanBuck** [comment]
You're welcome!
