### ISSUE TITLE
Relating games table to rounds table

### ISSUE THREAD

**Issue by richiecarey** [susanBuck/e2-fall22#47]
Hi all,

I have an autoplay game where a user selects the number of rounds they wish the game to run. 

http://e2p2.richiecarey.com/

A unique "game" is instantiated only when the user selects the number of rounds and clicks `Submit`.

For my final project, each record in my `games` table will relate to multiple records in the `rounds` table. I will need an `id` to accomplish this relationship but I'm unclear how best (or where in the flow of execution) to generate this unique game id.

I doubt this is correct but I considered inserting a new record in the `games` table first (immediately after `Submit` but before the rounds commence) and then retrieving and using the auto incremented `id` of that new record, but I'm actually not sure how I would query and return that record without knowing the `id` or some value to identify this record as _the_ record just created.

Suggestions? Thanks!

**Comment by susanBuck** [comment]
Hi @richiecarey -

I just pushed an update to the framework that makes it so that the database [_insert_](https://hesweb.dev/e2/notes/php/e2framework/database#insert) method returns the id of the row that was just inserted. 

From my understanding of what you described, I think this will help with what you're trying to achieve? 

If not, let me know and I can provider other suggestions. Otherwise, run `composer update` in the root of your project and you'll get this update and be able to put it to use.

**Comment by richiecarey** [comment]
That seems like what I will need .. thanks @susanBuck !

**Comment by susanBuck** [comment]
Closing this thread, but if there are any pending issues/questions feel free to re-open or start a new thread.
