### ISSUE TITLE
Github repo visibility

### ISSUE THREAD

**Issue by duyvhh** [susanBuck/e2-fall22#5]
Hi,

Do I have to make my main repo for this course (e2) to be public?

Can I set it to private and give access when requested?

thanks

**Comment by susanBuck** [comment]
It would be preferable if it were public so that when asking questions about your classmates would be able to look at the relevant code.

However, if you really want it to be private, it's not a requirement that it's public. If you do make it private, add my Github username (`susanBuck`) as a collaborator.

**Comment by micoso** [comment]
I was wondering the same thing.  Thanks duyvhh for asking.
