### ISSUE TITLE
Trouble with installing Codeception

### ISSUE THREAD

**Issue by andlearnmore** [susanBuck/e2-fall22#50]
Hi! When I got to the step of entering `php vendor/bin/codecept bootstrap` I got an error: 

```
File codeception.yml created       <- global configuration

In InitTemplate.php line 257:
                
  Syntax error  
                

bootstrap [-s|--namespace [NAMESPACE]] [-a|--actor [ACTOR]] [-e|--empty] [--] [<path>]
```
I tried again and subsequently got:

```
In InitTemplate.php line 201:
Codeception is already installed in this directory  
bootstrap [-s|--namespace [NAMESPACE]] [-a|--actor [ACTOR]] [-e|--empty] [--] [<path>]
```

I'd appreciate suggestions for fixing this so I can move forward. Thanks!!

**Comment by susanBuck** [comment]
FYI Going to log into your server now and take a look - will reply again shortly.

**Comment by susanBuck** [comment]
Hi @andlearnmore -

I took a look at your zipfoods directory and it looked like the codeception bootstrap process had installed the `tests` directory, but it wasn't complete - there were missing files. 

To straighten things out, I deleted the `tests` directory and the codeception config file (`codeception.yml`) then re-ran the bootstrap command (`php vendor/bin/codecept bootstrap`).

All appeared to go well because after it was done the `tests` directory was complete. You should be able to proceed forward with the next steps.

I'm not exactly sure why it failed for you. Could have been some sort of server blip? If the same thing happens again when you go to install testing in your P3, let me know. :)

**Comment by andlearnmore** [comment]
Thank you so much!
